version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=timetable_db
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=postgres_password

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  backend:
    build: ./timetable_generator
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./timetable_generator:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - POSTGRES_NAME=timetable_db
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_HOST=db

  frontend:
    build: ./timetable-frontend
    volumes:
      - ./timetable-frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8000

volumes:
  postgres_data: